### ISSUE TITLE
Provide Symbols and Sources along with NuGet package

### ISSUE THREAD

**Issue by Deilan** [fluentsprings/ExpressMapper#110]
Long story short: having symbols and sources sometimes helps a lot with debugging and troubleshooting. :)
Please provide symbols and sources along with "binaries".
Here's an article on NuGet.org on how to do it seamlessly while creating and deploying the nuget package:
https://docs.nuget.org/create/creating-and-publishing-a-symbol-package
Thanks in advance!

**Comment by anisimovyuriy** [comment]
@Deilan - thanks for your input! Will do in the next release.

**Comment by anisimovyuriy** [comment]
Included and released in 1.9.0
