### ISSUE TITLE
Improving AmbiguousMatchException

### ISSUE THREAD

**Issue by trx1** [fluentsprings/ExpressMapper#130]
When AmbiguousMatchException is thrown there is no information on what property the exception was thrown on. To help in debugging I suggest catching the exception (possibly in the AutoMapProperty function in TypeMapperBase.cs) and re-throw the exception but add what property threw the exception.

**Comment by anisimovyuriy** [comment]
There is a fix already for it - it will choose the right property from the most top subclass in the hierarchy.

**Comment by anisimovyuriy** [comment]
Fixed and will be included in 1.9.1 release!
