### ISSUE TITLE
Support .NET Core

### ISSUE THREAD

**Issue by bogatykh** [fluentsprings/ExpressMapper#17]

**Comment by nooxnet** [comment]
Just wanted to tell that I compiled the current source as .NET Core RC2 project (netstandard1.5 library). Currently I have not migrated or executed the tests. I don't know how .NET Core support should be integrated in the sources. If anybody is interested:

In DependencyResolver.cs:

`//var expressMapperAssembly = Assembly.GetExecutingAssembly();`

to

`var expressMapperAssembly = typeof(DependencyResolver).GetTypeInfo().Assembly;`

See: http://forums.asp.net/t/2001385.aspx?Assembly+GetExecutingAssembly+core

Further more the "full blown reflection type information" was removed from the Type class (see: https://www.infoq.com/news/2016/02/Core-Discontinued). ExpressMapper uses the reflection information for types heavily. To get the reflection properties and methods you can use `GetTypeInfo()`.

I've created Type extension methods  for methods used in ExpressMapper. They use GetTypeInfo(). 

As there are no extension properties I've replaced all code parts of the form
`type.TypeProperty`
with
`type.GetTypeInfo().TypeProperty`

If wanted I can provide additional code. 

What are the plans regarding .NETCore and ExpressMapper?

**Comment by Deilan** [comment]
Definitely highly requested enhancement. :)

**Comment by JonPSmith** [comment]
+1 from me for support of .NET Core

**Comment by anisimovyuriy** [comment]
Thanks a lot guys for inspiration :)
I'll try to get to it soon!

**Comment by rolandoldengarm** [comment]
Hi @anisimovyuriy This is a blocker for us, we've just upgraded to .NET Core. Any ETA when ExpressMapper will be compatible?

**Comment by anisimovyuriy** [comment]
Dear All,

My apologies for not responding during 2 last months as I have some business to be taken care of... And I appreciate you patience and contribution.

Ok, so far I can see there would be no issue to get .Net Core supported - it will be implemented today and I'll publish new version at EOD (Paciffic time).

Thanks for your support and patience,
Yours Yuriy

**Comment by rolandoldengarm** [comment]
That is AWESOME @anisimovyuriy 
Migrating to AutoMapper is a big effort, so it would be great if we could stay with EM :)

**Comment by anisimovyuriy** [comment]
Will be included in 1.8.2.

@rolandoldengarm - .Net core has already been pushed to repo as you can see - but I'm struggling to publish nuget package for .Net core and other targets like net40, net45... I'm investigating right now - hopefully will find solution by the EOD of tomorrow.

Thanks for your patience!

**Comment by anisimovyuriy** [comment]
Actually it's done just add this code in project.json (example):

```
{
  "version": "1.0.0-*",
  "buildOptions": {
    "debugType": "portable",
    "emitEntryPoint": true
  },
  "dependencies": {},
  "frameworks": {
    "netcoreapp1.6": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.0.0"
        },
        "Microsoft.AspNetCore.Server.Kestrel": "1.0.0",
        "Expressmapper":"1.8.2"
      },
      "imports": "dnxcore50"
    }
  }
}
```

**Comment by rolandoldengarm** [comment]
@anisimovyuriy AWESOME! You've made my day :dancer:

**Comment by JonPSmith** [comment]
Thanks @anisimovyuriy . Great News!

I am looking at a new project using Core and I thought I would have to use AutuoMapper, but now I can use ExpressMapper.

**Comment by mikebridge** [comment]
I'm confused---I'm targeting netcoreapp1.1 and I'm getting this error:

```
Package Expressmapper 1.9.1 is not compatible with netcoreapp1.1 (.NETCoreApp,Version=v1.1). Package Expressmapper 1.9.1 supports:
  - dotnet (.NETPlatform,Version=v5.0)
  - net40 (.NETFramework,Version=v4.0)
  - net45 (.NETFramework,Version=v4.5)
  - net46 (.NETFramework,Version=v4.6)
  - portable-monoandroid10+monotouch10+net45+win+win81+wp8+wpa81+xamarinios10 (.NETPortable,Version=v0.0,Profile=win+net45+wp80+win81+wpa81+MonoAndroid10+MonoTouch10+Xamarin.iOS10)
One or more packages are incompatible with .NETCoreApp,Version=v1.1.
```

**Comment by BAI-bmartinez** [comment]
I tried to add Expressmapper 1.9.1 to a .NET 5 project and it keeps giving me a warning. Can you please confirm if it's already compatible or not yet?
