### ISSUE TITLE
Add support for mapping by convention

### ISSUE THREAD

**Issue by mr-unicoder** [fluentsprings/ExpressMapper#22]
As our previous discussion on codeproject,
you need to add support for mapping by convention as it's a very important feature and already implemented in other frameworks.
It would be great also if you made convention rules extendable somehow :)

**Comment by mr-unicoder** [comment]
Will this be available soon ?

**Comment by mr-unicoder** [comment]
Is the project dead or something ?!!

**Comment by mr-unicoder** [comment]
Unfortunately, It was a very good start but ended very early, I'll switch back to the beloved AutoMapper.

**Comment by anisimovyuriy** [comment]
Dear @mr-unicoder,

My apologies for not responding for such a long time! I had some business to be take care of.
Thanks for your patience. Can you remind me about "mapping by convention" - is it flattening feature or something different?
Flattening feature has been already implemented in 1.8.1.

One more time - my apologies for not responding....

Thanks,
Yuriy

**Comment by mr-unicoder** [comment]
I don't know what "Flattening" feature means so I can't confirm if they're the same or not.
By "Mapping By Convention" I mean, mapping **Customer.Name** to **CustomerName** and **Employee.Id** to **EmployeeId** without any configuration.

**Comment by anisimovyuriy** [comment]
@mr-unicoder!
Yes it's the same feature we are talking about - I even haven't updated documentation yet but it's here. What you need to do is call ```.Flatten``` during registration.
Example:
```Mapper.Register<Test,TestViewModel>().Flatten();```
@JonPSmith is main contributor to this feature and he wrote an article with examples how to use flattening feature in Expressmapper: http://www.thereformedprogrammer.net/flattening-entity-framework-relationships-with-expressmapper/

Just let me know if you have any other questions...

Thanks you for your patience!

Gratefully Yours,
Yuriy

**Comment by anisimovyuriy** [comment]
I'm going to close the issue if you don't mind @mr-unicoder - but still you can reopen it if you feel that there is something that it's not implemented or you have any questions.

Thanks,
Yuriy
