### ISSUE TITLE
.NET Core: The type 'Object' is defined in an assembly that is not referenced

### ISSUE THREAD

**Issue by ZOXEXIVO** [fluentsprings/ExpressMapper#77]
The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e, Retargetable=Yes'.

Mapper.Register<Person, PersonDto>(); <---- this line

**Comment by anisimovyuriy** [comment]
Dear Ivan,

Unfortunately Expressmapper hasn't suppored ".Net Core" yet - but we've already planned that for <a href="https://github.com/expressmapper/ExpressMapper/issues/17">future release</a>.

Thanks for your input and understanding!

**Comment by anisimovyuriy** [comment]
Done - will be release in 1.8.2
